version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: healthcare_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zola
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthcare_network

volumes:
  postgres_data:

networks:
  healthcare_network:
